### ISSUE TITLE
Fazer o reconhecimento por kinect 

### ISSUE THREAD

**Issue by lucasrodrigues1410** [Caique-P/ReconhecimentoGestos#1]
Depois de instalar os drivers, pode ser que isso ajude
cv2.VideoCapture(0, cv2.CAP_OPENNI2)

**Comment by Caique-P** [comment]
Apenas atualizando: Consegui conectar o kinect ao windows, porém não ao python, ao que tudo indica vms usar a biblioteca freenect pra conectar os sensores do kinect ao python https://github.com/OpenKinect/libfreenect (preciso papirar mais pra entender sobre isso.)
![image](https://user-images.githubusercontent.com/58194653/174904053-72b5eb4c-3a63-406e-89d0-2e55db8313e5.png)

**Comment by Caique-P** [comment]
Problema resolvido nos ultimos patchs, via transmissão por obs.
